### ISSUE TITLE
install 관련 제안

### ISSUE THREAD

**Issue by item4** [php79/stack#1]
1. PHP 5.3, 5.4는 더 이상 업데이트 되지 않는 위험한 버전입니다. 설치하려고 할 경우 경고를 띄워주는건 어떨까요?
2. CentOS만 지원하는 것은 OS 다양성 측면에서 좋지 않다고 생각하는데 타 OS를 지원할 계획은 없으신가요?

**Comment by ibin79** [comment]
1. 우선 간략한 정보와 링크로 보완해두었습니다.
![image](https://cloud.githubusercontent.com/assets/6302755/14223737/14bd7e96-f8c0-11e5-8030-aeb7631fe010.png)

2. 초기에 우분투까지 잠시 고민해봤지만... 다음 2가지로 이유로 CentOS만 지원하기로 결정했습니다.
첫째. 제 주요 업무 환경이 CentOS 6/7 에 집중되어 있어, 제가 실제 사용하면서 개발할 수 있는 환경에 집중했습니다.
둘째. 우분투는 https://github.com/laravel/homestead 가 잘 만들어져 있어, 필요성이 상대적으로 낮다고 판단했습니다.

좋은 의견 감사합니다.
