### ISSUE TITLE
php 8 버전대 설치가 되지 않는 이유가 무엇일까요?

### ISSUE THREAD

**Issue by l2zeo** [php79/stack#103]
현재 아래처럼 실행했습니다. 결과에서 php 8 버전대가 설치되지 않고 있습니다.
이유를 알수가 없네요.

`
PHP53=0
PHP54=0
PHP55=0
PHP56=0
PHP70=0
PHP71=0
PHP72=0
PHP73=0
PHP74=1
PHP80=0
PHP81=1
PHP82=0

PHP_BASE=74

NGINX=1

LETSENCRYPT=1
`

` ./install.sh 

php79 stack version 1.3.2
  * PHP 5.3-8.2 + Nginx + Let's Encrypt + MariaDB installer

Install options:
  - Install EPEL repo / http://fedoraproject.org/wiki/EPEL
  - Install PHP 8.1 from Remi repo / http://rpms.famillecollet.com/
  - Install PHP 7.4 from Remi repo / http://rpms.famillecollet.com/
  - Set PHP CLI version ( /usr/bin/php ) : 74
  - Install Nginx 1.* from Nginx repo (stable) / http://nginx.org/en/linux_packages.html
  - Install Let's Encrypt tools (certbot-auto + configs) / https://certbot.eff.org/
  - Install MariaDB 10.6 from MariaDB repo (stable) / https://mariadb.com/kb/en/mariadb/yum/
  - Install smartmontools (physical server only)
  - Install lm_sensors (physical server only)
  - Install developer tools (wget, rsync, nslookup, ...)
  - Change time zone Asia/Seoul for /etc/localtime, php.ini
  - Interactive mode

Do you want to install? (위 패키지들을 설치하시겠습니까?) [n/Y] Y

‘/usr/bin/php’ -> ‘/usr/bin/php74’

Thanks for php79 stack installing.  (설치가 완료되었습니다.)
Visit http://127.0.0.1 or http://ServerIP

Check the installation status? (설치 상태를 확인하시겠습니까?) [Y/n] Y

php79 stack version 1.3.2

- php.ini
/etc/opt/remi/php71/php.d/z-php79.ini
/etc/opt/remi/php74/php.d/z-php79.ini
/opt/remi/php54/root/etc/php.d/z-php79.ini
- nginx
/etc/nginx/conf.d/0-php79.conf
- MariaDB
/etc/my.cnf.d/z-php79.cnf

  * php.d/z-php79.ini, my.cnf.d/z-php79.cnf 파일들은 파일 이름순 정렬로 마지막에 로딩됩니다.
  * php.ini 와 php.d/z-php79.ini 2개에 같은 설정이 있다면, 마지막에 로드된 php.d/z-php79.ini 설정이 적용됩니다.
  * 따라서 설정 변경시엔 php.ini 대신, php.d/z-php79.ini 파일을 수정해야 합니다.

CLI path     	Version		Service name
/usr/bin/php	7.4.33		php74-php-fpm
/usr/bin/php54	5.4.45		php54-php-fpm
/usr/bin/php71	7.1.33		php71-php-fpm
/usr/bin/php74	7.4.33		php74-php-fpm

  * PHP FPM 재시작 명령: systemctl restart php74-php-fpm

Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:9054          0.0.0.0:*               LISTEN      962/php-fpm: master 
tcp        0      0 127.0.0.1:9071          0.0.0.0:*               LISTEN      958/php-fpm: master 
tcp        0      0 127.0.0.1:9074          0.0.0.0:*               LISTEN      2865/php-fpm: pool  

Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      13676/nginx: master 
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      13676/nginx: master 
tcp6       0      0 :::80                   :::*                    LISTEN      13676/nginx: master 

curl http://127.0.0.1 -> 

  * Nginx 재시작 명령: systemctl restart nginx

Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:3306            0.0.0.0:*               LISTEN      12322/mariadbd      
tcp6       0      0 :::3306                 :::*                    LISTEN      12322/mariadbd      

mysqladmin ping -> mysqld is alive

  * MariaDB 재시작 명령: systemctl restart mariadb
`

**Comment by 742soft** [comment]
CentOS 9에서도 앞의 것은 다 설치가 되는데, php82가 설치가 안되더라구요.ㅠㅠ

**Comment by ibin79** [comment]
CentOS 7 에서 다음 2개를 활성화해보니 PHP 8.1 이 잘 설치됩니다만...

```
PHP74=1
PHP81=1
```

![image](https://github.com/php79/stack/assets/6302755/c204aeb8-18c8-4955-9bdb-f526ee5e40e5)


yum history 를 확인해봐도 특이사항이 없어보이는데요.

```
[root@localhost stack]# yum history 
Loaded plugins: fastestmirror, product-id, search-disabled-repos, subscription-manager

This system is not registered with an entitlement server. You can use subscription-manager to register.

ID     | Command line             | Date and time    | Action(s)      | Altered
-------------------------------------------------------------------------------
    33 | -y install php81-php-cli | 2024-02-14 16:49 | Install        |   14   
    32 | -y install php74-php-cli | 2024-02-14 16:49 | Install        |   93 EE
    31 | -y install http://rpms.r | 2024-02-14 16:48 | Install        |    1  

[root@localhost stack]# yum history info 33
Loaded plugins: fastestmirror, product-id, search-disabled-repos, subscription-manager

This system is not registered with an entitlement server. You can use subscription-manager to register.

Transaction ID : 33
Begin time     : Wed Feb 14 16:49:51 2024
Begin rpmdb    : 607:2b3e9f529d02d2f486781620d0dc9a1d5173246a
End time       :            16:49:56 2024 (5 seconds)
End rpmdb      : 621:d1bf372935759eea07a01c387aa58d877ffb80f9
User           : root <root>
Return-Code    : Success
Command Line   : -y install php81-php-cli php81-php-fpm php81-php-common php81-php-pdo php81-php-mysqlnd php81-php-mbstring php81-php-mcrypt php81-php-opcache php81-php-xml php81-php-pecl-imagick php81-php-gd php81-php-fileinfo php81-php-pecl-zip php81-php-bcmath
Transaction performed with:
    Installed     rpm-4.11.3-48.el7_9.x86_64                       @updates
    Installed     subscription-manager-1.24.53-1.el7.centos.x86_64 @updates
    Installed     yum-3.4.3-168.el7.centos.noarch                  @base
    Installed     yum-plugin-fastestmirror-1.1.31-54.el7_8.noarch  @base
Packages Altered:
    Install     php81-php-bcmath-8.1.27-1.el7.remi.x86_64          @remi
    Install     php81-php-cli-8.1.27-1.el7.remi.x86_64             @remi
    Install     php81-php-common-8.1.27-1.el7.remi.x86_64          @remi
    Install     php81-php-fpm-8.1.27-1.el7.remi.x86_64             @remi
    Install     php81-php-gd-8.1.27-1.el7.remi.x86_64              @remi
    Install     php81-php-mbstring-8.1.27-1.el7.remi.x86_64        @remi
    Install     php81-php-mysqlnd-8.1.27-1.el7.remi.x86_64         @remi
    Install     php81-php-opcache-8.1.27-1.el7.remi.x86_64         @remi
    Install     php81-php-pdo-8.1.27-1.el7.remi.x86_64             @remi
    Install     php81-php-pecl-imagick-im6-3.7.0-7.el7.remi.x86_64 @remi
    Install     php81-php-pecl-mcrypt-1.0.7-1.el7.remi.x86_64      @remi
    Install     php81-php-pecl-zip-1.22.3-1.el7.remi.x86_64        @remi
    Install     php81-php-xml-8.1.27-1.el7.remi.x86_64             @remi
    Dep-Install php81-runtime-8.1-4.el7.remi.x86_64                @remi
```

다음처럼 PHP 8.1 설치 스크립트를 직접 실행해보는 것도 한 방법일 듯 합니다.

```
[root@localhost scripts]# cd /root/stack/scripts/
[root@localhost scripts]# ./php8-remi-install.sh 81

### PHP [81] 버전을 설치합니다. ###

Loaded plugins: fastestmirror, product-id, search-disabled-repos, subscription-manager

This system is not registered with an entitlement server. You can use subscription-manager to register.

Loading mirror speeds from cached hostfile
 * base: mirror.kakao.com
 * epel: ftp.iij.ad.jp
 * extras: mirror.kakao.com
 * remi: cdn.centos.no
 * remi-safe: cdn.centos.no
 * updates: mirror.kakao.com
Package php81-php-cli-8.1.27-1.el7.remi.x86_64 already installed and latest version
Package php81-php-fpm-8.1.27-1.el7.remi.x86_64 already installed and latest version
Package php81-php-common-8.1.27-1.el7.remi.x86_64 already installed and latest version
Package php81-php-pdo-8.1.27-1.el7.remi.x86_64 already installed and latest version
Package php81-php-mysqlnd-8.1.27-1.el7.remi.x86_64 already installed and latest version
Package php81-php-mbstring-8.1.27-1.el7.remi.x86_64 already installed and latest version
Package php81-php-pecl-mcrypt-1.0.7-1.el7.remi.x86_64 already installed and latest version
Package php81-php-opcache-8.1.27-1.el7.remi.x86_64 already installed and latest version
Package php81-php-xml-8.1.27-1.el7.remi.x86_64 already installed and latest version
Package php81-php-pecl-imagick-3.4.4-18.el7.remi.x86_64 is obsoleted by php81-php-pecl-imagick-im6-3.7.0-7.el7.remi.x86_64 which is already installed
Package php81-php-gd-8.1.27-1.el7.remi.x86_64 already installed and latest version
Package php81-php-common-8.1.27-1.el7.remi.x86_64 already installed and latest version
Package php81-php-pecl-zip-1.22.3-1.el7.remi.x86_64 already installed and latest version
Package php81-php-bcmath-8.1.27-1.el7.remi.x86_64 already installed and latest version
Nothing to do
`/var/opt/remi/php81/lib/php/opcache'의 그룹이 nobody으로 보존되었습니다
`/var/opt/remi/php81/lib/php/session'의 그룹이 nobody으로 보존되었습니다
`/var/opt/remi/php81/lib/php/wsdlcache'의 그룹이 nobody으로 보존되었습니다
ownership of `/var/opt/remi/php81/log/php-fpm' retained as nobody
```

**Comment by 742soft** [comment]
로키 8 이었습니다 ㅠㅠ

**Comment by ibin79** [comment]
Rocky 8.9 에서 지금 해봐도 설치가 잘 되는데요.

![image](https://github.com/php79/stack/assets/6302755/f1fb1422-2639-41d6-afb6-bc70182c0c70)

설치시 에러가 났거나 삭제후 재설치해야하는 경우라면, 다음 중복 실행 방지용 락 파일을 직접 삭제후 install.sh 를 실행해주시면 됩니다.

```
[root@rocky87 stack]# ll /root/stack/locks/*php*
-rw-r--r--. 1 root root 0 11월 23 07:41 /root/stack/locks/scripts_php-composer-install.sh
-rw-r--r--. 1 root root 0 11월 23 07:41 /root/stack/locks/scripts_php7-remi-install.sh_74
-rw-r--r--  1 root root 0  2월 18 18:28 /root/stack/locks/scripts_php8-remi-install.sh_80
-rw-r--r--  1 root root 0  2월 18 18:27 /root/stack/locks/scripts_php8-remi-install.sh_81
-rw-r--r--  1 root root 0  2월 18 18:27 /root/stack/locks/scripts_php8-remi-install.sh_82
```
