### ISSUE TITLE
어제부터 MariaDB 저장소 설치 부분이 막힙니다.

### ISSUE THREAD

**Issue by composerent** [php79/stack#104]
### MariaDB 저장소를 설치합니다. ###

curl: (6) Could not resolve host: r.mariadb.com

### MariaDB 10.11 을 설치합니다. ###

마지막 메타자료 만료확인(0:01:25 이전): 2024년 09월 03일 (화) 오전 12시 44분 20초.
일치하는 인수가 없습니다: MariaDB-server
  * 다음을 의미 할 수도 있습니다: mariadb-server
일치하는 인수가 없습니다: MariaDB-client
일치하는 인수가 없습니다: MariaDB-common
  * 다음을 의미 할 수도 있습니다: mariadb-common
일치하는 인수가 없습니다: MariaDB-compat
일치하는 인수가 없습니다: MariaDB-shared
오류: 일치하는 항목을 찾을 수 없습니다: MariaDB-server MariaDB-client MariaDB-common MariaDB-compat MariaDB-shared

Notice) MariaDB 기본 캐릭터셋이 utf8mb4 로 지정되었습니다.
설정 파일 경로) /etc/my.cnf.d/z-php79.cnf

'/root/stack/mariadb/z-php79.cnf' -> '/etc/my.cnf.d/'
cp: cannot create regular file '/etc/my.cnf.d/': Not a directory
Failed to enable unit: Unit file mariadb.service does not exist.
Failed to start mariadb.service: Unit mariadb.service not found.
scripts/mariadb-install.sh: line 54: /usr/bin/mariadb-secure-installation: No such file or directory
다음 명령이 실패하여, 설치가 중단되었습니다. (exit code: 127)
# scripts/mariadb-install.sh 

위처럼 오류가 발생합니다. 오류를 수정하려면 어디를 수정해야 하는지 궁금합니다.

또한, rocky linux 9.x 버전과 Red Hat Linux 8.x 버전에서 설치를 희망하는데 이 부분도 어디를 수정해야 하는지 궁금합니다.

php79로 구축을 편하게 하고 있습니다. 항상 감사드립니다!

**Comment by ibin79** [comment]
오류 원인은 MariaDB 저장소 설치가 다음 에러로 되지 않기 때문인데요.

`curl: (6) Could not resolve host: r.mariadb.com`


MariaDB 서버 장애인지, 동일한 이슈가 어제 올라와 있습니다.

https://jira.mariadb.org/browse/MDEV-34853?filter=-4


위 이슈의 댓글을 참고해서, 임시 방편으로 MariaDB 저장소를 직접 설치하시면 될 것 같습니다.

```sh
curl -LsS https://dlm.mariadb.com/3/MariaDB/mariadb_repo_setup | sudo bash -s -- --mariadb-server-version="mariadb-10.11"
```

> 참고) MariaDB 저장소 설치 스크립트) https://github.com/php79/stack/blob/master/scripts/mariadb-repo-install.sh#L15

---

Rocky Linux 9 는 아직 지원하지 않습니다.

RHEL 8 은 dnf 저장소 변경 및 릴리즈 파일 링크( /etc/redhat-release -> rocky-release ) 후 시도로 테스트가 필요해 보입니다.

> 참고) https://github.com/php79/stack/blob/master/includes/function.inc.sh#L28

**Comment by ibin79** [comment]
https://r.mariadb.com/downloads/mariadb_repo_setup 다운로드 오류건은 해결되었다고 합니다.

![image](https://github.com/user-attachments/assets/48e665c9-54e4-45fb-bbad-0d31d3eff43e)

**Comment by composerent** [comment]
@ibin79 ### MariaDB 10.11 을 설치합니다. ###

MariaDB MaxScale                                 93  B/s | 109  B     00:01    
Errors during downloading metadata for repository 'mariadb-maxscale':
  - Status code: 404 for https://dlm.mariadb.com/repo/maxscale/latest/yum/rhel/8/x86_64/repodata/repomd.xml (IP: 104.17.191.14)
오류: repo를 위한 메타자료 내려받기에 실패하였습니다 'mariadb-maxscale': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried

Notice) MariaDB 기본 캐릭터셋이 utf8mb4 로 지정되었습니다.
설정 파일 경로) /etc/my.cnf.d/z-php79.cnf

'/root/stack/mariadb/z-php79.cnf' -> '/etc/my.cnf.d/'
cp: cannot create regular file '/etc/my.cnf.d/': Not a directory
Failed to enable unit: Unit file mariadb.service does not exist.
Failed to start mariadb.service: Unit mariadb.service not found.
scripts/mariadb-install.sh: line 54: /usr/bin/mariadb-secure-installation: No such file or directory
다음 명령이 실패하여, 설치가 중단되었습니다. (exit code: 127)
# scripts/mariadb-install.sh 

해결 이후 위와 같은 오류가 추가 발생합니다.

이것도 마리아 쪽 서버 오류일까요? ㅜㅜ
