### ISSUE TITLE
MariaDB 설치 중 오류

### ISSUE THREAD

**Issue by composerent** [php79/stack#106]
### MariaDB 10.11 을 설치합니다. ###

Rocky Linux 8 - AppStream                        17 MB/s |  12 MB     00:00    
Rocky Linux 8 - BaseOS                          6.9 MB/s | 6.1 MB     00:00    
Rocky Linux 8 - Extras                           20 kB/s |  14 kB     00:00    
Extra Packages for Enterprise Linux 8 - x86_64   16 MB/s |  14 MB     00:00    
MariaDB Server                                  418 kB/s | 620 kB     00:01    
MariaDB MaxScale                                112  B/s | 109  B     00:00    
Errors during downloading metadata for repository 'mariadb-maxscale':
  - Status code: 404 for https://dlm.mariadb.com/repo/maxscale/latest/yum/rhel/8/x86_64/repodata/repomd.xml (IP: 104.17.191.14)
오류: repo를 위한 메타자료 내려받기에 실패하였습니다 'mariadb-maxscale': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried

Notice) MariaDB 기본 캐릭터셋이 utf8mb4 로 지정되었습니다.
설정 파일 경로) /etc/my.cnf.d/z-php79.cnf

'/root/stack/mariadb/z-php79.cnf' -> '/etc/my.cnf.d/'
cp: cannot create regular file '/etc/my.cnf.d/': Not a directory
Failed to enable unit: Unit file mariadb.service does not exist.
Failed to start mariadb.service: Unit mariadb.service not found.
scripts/mariadb-install.sh: line 54: /usr/bin/mariadb-secure-installation: No such file or directory
다음 명령이 실패하여, 설치가 중단되었습니다. (exit code: 127)
# scripts/mariadb-install.sh 

위 해당 오류가 추가 발생합니다.

이 오류는 어찌 해결해야 할까요?

**Comment by ibin79** [comment]
MariaDB yum 저장소가 불안정한 데, 현재는 위 링크가 잘 열리고 있습니다.


저장소 접속 오류 이슈는 다음처럼 아카이빙 주소로 임시 변경하는 방법이 있습니다.

### 저장소 수정 - `vi /etc/yum.repos.d/mariadb.repo`

1. mariadb-maxscale 저장소 비활성화


```
[mariadb-maxscale]

#enabled = 1
enabled = 0
```

2. mariadb-main 저장소 변경 - Rocky LInux 8


```
[mariadb-main]
name = MariaDB Server
#baseurl = https://dlm.mariadb.com/repo/mariadb-server/10.11/yum/rhel/8/x86_64
baseurl = https://archive.mariadb.org/yum/10.11/rockylinux8-amd64
```

2. mariadb-main 저장소 변경 - CentOS 7


```
[mariadb-main]
name = MariaDB Server
#baseurl = https://dlm.mariadb.com/repo/mariadb-server/10.11/yum/rhel/7/x86_64
baseurl = https://archive.mariadb.org/yum/10.11/rhel7-amd64
```


### MariaDB 설치 직접 실행

```sh
cd /root/stack/scripts
./mariadb-install.sh
```
