### ISSUE TITLE
DB root 패스워드 변경후 /root/.my.cnf 도 변경을 해야 하는지요?

### ISSUE THREAD

**Issue by hot5g** [php79/stack#18]
제목대로, 
db root 패스워드를 변경했습니다
`mysqladmin -p'새패스워드' password`

계정을 생성하려고 하는데. 아래와 같은 에러 문구가 출력됩니다.

```
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)

[ 새로운 계정 ] 디비 계정 생성이 실패하였습니다.

Exiting installer. (설치를 중단합니다.)

시스템 계정 추가 작업이 실패하였습니다.

Exiting installer. (설치를 중단합니다.)
```

계정 생성 방식은 아래 둘다 모두 이용해봤습니다. 동일합니다.

```
./app-install.sh --user=계정명 --password='계정 비밀번호' --domain=도메인 --app=gnuboard5 --php=70


./user-add.sh --user=계정명 --password='계정 비밀번호'
```

헌데 mysql -u root -p  로 하면 바뀐 패스워드로 접속이 됩니다;;

**Comment by ibin79** [comment]
네. /root/.my.cnf  에서도 함께 변경해주셔야 합니다.

디비 계정 생성시 mysql root 비밀번호를 입력 받지 않는 이유가 /root/.my.cnf 설정을 사용하기 때문입니다.

**Comment by hot5g** [comment]
@ibin79  답변 감사드립니다. 

그전에 mysqladmin -p'새패스워드' password 이런식으로 비밀번호를 변경했는데요.

변경된 비밀번호를 말씀주신대로 /root/.my.cnf 에 입력하였습니다.

여전히 계정 생성시 아래와 같은 에러구문이 출력되네요.

`ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)`

**Comment by ibin79** [comment]
우선 /root/.my.cnf 에 입력된 비밀번호가 정확한지 확인하려면 다음 처럼 mysql 접속을 시도해 보세요.

```
# mysql -uroot mysql
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 157519
Server version: 10.1.17-MariaDB MariaDB Server

Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [mysql]> 
```

그리고 `mysqladmin -p'새패스워드' password` 에서 '새패스워드'가 아니라 '현재 비밀번호'입니다만...

**Comment by hot5g** [comment]
@ibin79  이상하네요. 말씀주신거처럼 mysql -uroot mysql 입력해보았지만 비밀번호가 틀렸다고 합니다.
분명 mysql -uroot -p 로 해서 접속할때는 바뀐 비밀번호로 접속이 되는데 말이죠.
바뀐 비밀번호는 /root/.my.cnf 에 있는 비밀번호와 동일하구요.

```
[root@localhost ~]# mysql -uroot mysql
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
```

```
[root@localhost ~]# mysql -uroot -p
Enter password: 
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 7684
Server version: 10.1.18-MariaDB MariaDB Server

Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]>
``` 

말씀하신, `mysqladmin -p'새패스워드' password`  에서 새 패스워드는 바뀐 비밀번호(현재)를 말씀드린것이였습니다 ^^;;;

**Comment by hot5g** [comment]
@ibin79  안녕하세요. 위 내용을 작성하고 다시 새로운 패스워드로 변경하고 /root/.my.cnf 에도 변경한 패스워드를 입력/저장 하였으나 같은 증상이네요;

혹 db 재시작시 나오는 err 파일 관련 메세지와 연관이 있는것인지요?

```[root@localhost ~]# mysqladmin -p'기존패스워드' password
New password: 
Confirm new password: 
[root@localhost ~]# vi /root/.my.cnf
[root@localhost stack]# service mysql restart
Shutting down MySQL..                                      [  OK  ]
Starting MySQL.161108 11:31:30 mysqld_safe Logging to '/var/lib/mysql/localhost.localdomain.err'.
                                                           [  OK  ]```

**Comment by ibin79** [comment]
비밀번호에 특수문자가 포함되어 .my.cnf 에 입력한 비밀번호가 정상 인식되지 않는 상황이 아닐까요?

**Comment by hot5g** [comment]
@ibin79  안녕하세요. 말씀해주신거처럼 패스워드에 특문 !@# 이 들어가 있어서 인식이 안되었나봅니다.
특문을 제외한 새로운 패스워드를 생성하고 /root/.my.cnf 에 작성해서 알려주신 mysql -uroot mysql 해보니
바로 접근이 되네요;

감사합니다 ^^
