### ISSUE TITLE
DOCUMENT_ROOT 를 변경하려 합니다

### ISSUE THREAD

**Issue by hot5g** [php79/stack#20]
안녕하세요. 현재 DOCUMENT_ROOT 가 /home/aaa/public 으로 public 뒤에 슬러쉬를 붙게 수정하려 합니다.

vi /etc/nginx/conf.d/aaa.conf 에서 수정을 해보았지만 적용이 되지 않아, 혹 다른곳에서 수정을 해야 하는건지 여쭤봅니다.

수정전: 
```
server {
    set $APP_BACKEND php56_backend;
    #set $APP_BACKEND php70_backend;

    listen       80;
    server_name aaa.net www.aaa.net;
    root   /home/aaa/master/public;
...
```

수정후: 
```
server {
    set $APP_BACKEND php56_backend;
    #set $APP_BACKEND php70_backend;

    listen       80;
    server_name aaa.net www.aaa.net;
    root   /home/aaa/master/public/;
...
```

**Comment by ibin79** [comment]
`public/`처럼 뒤에 `/`를 덧 붙이려는 이유가 무엇인가요?

**Comment by hot5g** [comment]
@ibin79  
php 프로그램을 사용중인데. $_SERVER['DOCUMENT_ROOT'] 를 사용해서 경로를 맞춰놨더니.
현재 설치된곳의 환경과 기존의 설치된 환경이 틀려서 맞춰주려고 합니다.

**Comment by ibin79** [comment]
해당 값에 '/'을 덧 붙이려는 시도는 해보질 않아 잘 모릅니다만...

서버단이 아닌 php 소스단에서의 처리가 필요해 보입니다.

**Comment by hot5g** [comment]
@ibin79  stack 프로젝트와 상관없는 질문에 친절한 답글 감사드립니다.
'/' 를 덧붙여봐도 변함이 없기에 여쭤보았습니다.^^;;

말씀주신거처럼 php 소스단에서 처리해야 할거 같네요. 감사합니다!
