### ISSUE TITLE
php-fpm config 파일 수정관련.

### ISSUE THREAD

**Issue by hot5g** [php79/stack#21]
사이트 접속자가 적지 않은 상황이고 이미지가 많은 사이트다보니 
튜닝을 해야 할거 같은데요. 현재 기본설치만으로도 가능할지 여쭤봅니다.
(너무 모호한 질문인거 같네요.;)

그래서 php fpm의 config를 수정하려 하는데요.
혹 사이트마다 따로 분리가 되었는지를 알고 싶습니다.
그렇다면 해당 파일의 위치가 어디인지...;

제가 수정하려는것은 
max_children,rlimit_files 파일를 수정하려합니다.

서버사양을 좀 적어보자면,
CPU : Quad_2.40*2 8코어
메모리 32G
SSD : 128G*4 레이드1+0
HD: 2TB  (/home 마운트 사용)
HD:2TB (/backup 마운트 사용)

**Comment by ibin79** [comment]
현재 status.sh 에선 php-fpm 설정 파일 위치가 나오지 않는군요...^^

PHP 버전별로 `www.conf` 설정 1개씩이 기본 제공됩니다.

# PHP 버전별 php-fpm.d 디렉토리를 찾는 방법

```
# find / -type d -name 'php-fpm.d'
/etc/opt/remi/php70/php-fpm.d
/etc/php-fpm.d
/opt/remi/php56/root/etc/php-fpm.d
/opt/remi/php54/root/etc/php-fpm.d
/opt/remi/php55/root/etc/php-fpm.d
```

사이트마다 분리하거나 설정 값 튜닝은 아직 자료가 준비되지 않아, 다른 자료들을 찾아보셔야 할 것 같고요.

**Comment by hot5g** [comment]
@ibin79  php-fpm 위치가 나오지 않아서 여쭤봤는데. 감사합니다.^^

조만간 설정값 튜닝 자료도 올라오길 기대하겠습니다.!
