### ISSUE TITLE
./status.sh 명령 입력후 상태정보가 나오지 않습니다.

### ISSUE THREAD

**Issue by hot5g** [php79/stack#22]
우선 저만 너무 질문을 드리는거 같아서 죄송스럽습니다;
(다른분들은 잘 사용하고 계신데..저만 ;;)

본론으로 들어가자면,
정확히 언제부터인지는 모르겠습니다. 분명한것은 상태정보가 나왔었다는..

언제부터인지 ./status.sh 입력을 해도 스샷처럼 저 상태에서 멈춰있더라구요.

혹시 살펴봐야할 부분이 있을까요?..

ps.추후 대중적인(?)모듈를 추가 하실 계획이 혹시 있으신지요.
캐시관련 플러그인인 apc, redis, memcache, memcached 와 같은...

**Comment by ibin79** [comment]
@hot5g 스샷이 없습니다. ^^

redis 는 고려중이긴 합니다만...  아직 일정은 잡히지 않은 상태입니다.

**Comment by hot5g** [comment]
@ibin79  스샷이 없었군요;; 다시 올립니다.

![k-001](https://cloud.githubusercontent.com/assets/23052787/20750007/0eb236ae-b738-11e6-950a-d0cdfddbb245.png)

**Comment by ibin79** [comment]
서버에 파일수가 많아 다음 find 명령에서 부하가 걸리는 것 같습니다.
현재 터미널을 유지한 상태로 새 터미널로 접속하여 `htop`을 실행해 프로세스 상태를 보실 수 있습니다.

일단 아래 라인을 주석 처리하셔서 생략하시고, 개선 방안을 찾아보도록 하겠습니다.

https://github.com/php79/stack/blob/master/status.sh#L15

**Comment by hot5g** [comment]
@ibin79  감사합니다. 알려주신대로 주석처리후 ./status.sh 출력됩니다.

htop 를 통해 보았지만, 보통(?)의 웹서버와 다른게 크게 없어보이네요.
![k-001](https://cloud.githubusercontent.com/assets/23052787/20788151/da9a279e-b7f2-11e6-9398-52d7bd53ae72.png)

**Comment by ibin79** [comment]
find 명령의 부하는 대부분 디스크 io 라서...
Loadavg 나 iowait 등을 봐야합니다만...

생각해보니 io쪽은 glances 나 iotop으로 보시는 것이 편리할 것 같네요.

**Comment by hot5g** [comment]
@ibin79  그렇군요;; 혹 현재 디스크 하나로만 사용하고 있어서 그럴수도 있을까요.
디스크 추가후에 home 폴더 마운트해서 사용하려고 합니다. 그럼 나아질수도...?;

![k-001](https://cloud.githubusercontent.com/assets/23052787/20806998/7bd73096-b840-11e6-9f02-bd2c2baaaff7.png)

**Comment by ibin79** [comment]
디렉토리 1개에 1개의 파티션만 마운트할 수 있어, 후자가 맞습니다.

다만 주석 처리한 소스를 보시면, /home 파티션은 검색하지 않기 때문에 현재 이슈와는 무관해 보입니다.

**Comment by hot5g** [comment]
@ibin79  감사합니다

**Comment by l2zeo** [comment]
해당 이슈에 대한 개선은 아직인건지요?

**Comment by ibin79** [comment]
@l2zeo 이슈가 닫혀 저도 잊고 있었네요.    다시 알려주셔서 감사합니다.

우선 develop 브랜치에 해결해놨고요.

정식 배포는 테스트후에 다음 버전에 적용 예정입니다.(다음달로 예상중입니다...)


---

#### 개발 버전 적용 안내

개발 버전으로 서버를 업데이트하려면 다음처럼 git pull 에서 브랜치를 정의해주시면 됩니다.

```
cd /root/stack/ && git pull origin develop
```

> 제가 운영중인 서버엔 개발 브랜치를 적용해두었고요. 테스트후 문제없다고 예상되면 정식 배포(master branch)하고 있습니다.

**Comment by l2zeo** [comment]
@ibin79  감사합니다. 정식배포되면 업데이트 해야겠네요 :) 수고 많으셨습니다!

**Comment by l2zeo** [comment]
@ibin79 해당 이슈에 대한 정식배포는 언제쯤 이루어질까요? :)
최근 개선으로 분리된 모듈 관련도 궁금합니다.

**Comment by ibin79** [comment]
벌써 6개월 가까이 지났었군요.   일단 바쁜 일이 정리되어 가고 있어서, 8월달 내엔 최종 테스트후 정식 배포될 것으로 예상됩니다.

많이 기다리게 해드렸네요. ^^

**Comment by l2zeo** [comment]
@ibin79  stack 의존성이 커져서..ㅎ; 감사드립니다^^
