### ISSUE TITLE
외부모듈 추가 관련 문의

### ISSUE THREAD

**Issue by hot5g** [php79/stack#24]
Nginx 의 경우 외부모듈를 추가할때 새롭게 빌드를 해야 한다고 하던데. php79 stack 도 마찬가지인가요?

마찬가지라면, 외부 모듈 추가시 새롭게 빌드할때는 어떻게 해야 하는지요??

휴일 잘 보내세요^^!

**Comment by ibin79** [comment]
stack 은 nginx 공식 저장소의 rpm 을 자동 설치 + 권장 설정 +  앱 추가 기본 nginx 설정을 제공하는 역할만 합니다.

따라서 소스 컴파일해서 설치하려면, rpm 으로 설치된 nginx 를 삭제해야해서 stack 내에서 다루긴 어렵지 않나 생각됩니다.

**Comment by hot5g** [comment]
@ibin79 말씀 감사합니다. 그렇다면 외부모듈 추가에 대한 방안이 없다고 생각해야 할까요.
stack 으로 설치하지 말아야 하는거겠군요..?

**Comment by ibin79** [comment]
네.  현재로선 nginx 컴파일 지원을 위한 문서나 작업은 고려하지 않고 있습니다.

**Comment by hot5g** [comment]
@ibin79 아..그렇군요. nginx 에 외부모듈 1~2개를 사용할일이 생길거 같아서 미리 여쭤봤습니다.
해당 외부모듈를 꼭 사용해야 한다면 재설치를 해야겠네요. 말씀 감사드립니다.
