### ISSUE TITLE
z-php79.ini 의 에러 레벨설정이 적용되지 않는거 같습니다.

### ISSUE THREAD

**Issue by hot5g** [php79/stack#29]
z-php79.ini 에서 에러 출력 레벨를 아래처럼 설정했습니다.

`error_reporting = E_COMPILE_ERROR|E_ERROR|E_CORE_ERROR`

변수가 없어서 나오는 warning 문구를 제외하려 하거든요.

php-fpm 재시작과 nginx 재시작을 했는데도 여전히 에러 로그에 기록되더라구요.

/opt/remi/php56/root/var/log/php-fpm/www-error.log

또 다른부분을 설정해야 하는지요?

**Comment by ibin79** [comment]
알려주신 에러 설정은 테스트해보지 못했고요.

일반적인 변수 미선인시 에러인 E_NOTICE 을 제외하는 설정은 다음과 같습니다.

```
error_reporting = E_ALL & ~E_DEPRECATED & ~E_NOTICE  ; 레거시 호환용.  선언되지 않은 변수 사용시 에러 등 숨김.
```

E_WARNING 까지 생략하려면 다음과 같고요.

```
error_reporting = E_ALL & ~E_DEPRECATED & ~E_NOTICE & ~E_WARNING  ; 레거시 호환용.  PHP 5.3.3 에선 E_DEPRECATED 가 E_WARNING 으로 처리되는 에러 보완 목적
```


만약 위 서버단 설정적용하고 php-fpm 재시작후에도 문제가 해결되지 않는다면...

PHP 소스내에서 error_reporting() 함수를 통해 에러 레벨을 재정의했을 가능성을 살펴봐야 합니다.

**Comment by ibin79** [comment]
참고로 다음처럼 z-php79.ini 파일에서 error_reporting 설정이 정상 적용되는 것은 지금 확인했습니다.

```
vim /opt/remi/php56/root/etc/php.d/z-php79.ini
systemctl reload php56-php-fpm
```

**Comment by hot5g** [comment]
@ibin79 
감사합니다. 확인해보니 php소스파일내에 에러리포팅을 따로 정의해두었네요;;
죄송합니다;
