### ISSUE TITLE
가상서버 사용중인데요 에러 문의 드립니다.

### ISSUE THREAD

**Issue by ChoHanDu** [php79/stack#30]
OS: CentOS Linux release 7.3.1611 
cafe24 가상서버 사용중입니다.
ntpdate[30522]: no server suitable for synchronization found
혹시 어디를 수정해보면 될지 문의드립니다.

**Comment by ibin79** [comment]
서버에서 다음 명령의 실행 결과를 알 수 있을까요?

`ntpdate -v -u kr.pool.ntp.org 0.centos.pool.ntp.org pool.ntp.org`


참고로 에러 위치는 https://github.com/php79/stack/commit/1b5461e31240fed382b4faf7343b87a12ec2f3c7 의 ntpdate 명령입니다.

**Comment by ChoHanDu** [comment]
[root@q352-1966 stack]# ntpdate -v -u kr.pool.ntp.org 0.centos.pool.ntp.org pool               .ntp.org
21 Mar 12:21:40 ntpdate[30895]: ntpdate 4.2.6p5@1.2349-o Mon Feb  6 07:34:44 UTC                2017 (1)
21 Mar 12:21:50 ntpdate[30895]: no server suitable for synchronization found

**Comment by ibin79** [comment]
https://github.com/php79/stack/issues/13#issuecomment-248776069 케이스처럼...

ntpdate 로 시간 동기화가 이루어지지 않는 원인은, 서버 자체 혹은 서버 앞단의 방화벽에서  '외부로 나가는 udp 123 포트'가 차단되었기 때문으로 보입니다.

서버 앞단 방화벽은 카페24 고객센터에 위 명령의 실행 결과와 함께 문의가 필요합니다.

---

두번째 올려주신 테스트 결과는 단순히 `pool .ntp.org`로 중간에 공백이 들어가 발생한 오류로 무시하시고요.

**Comment by ChoHanDu** [comment]
네 고맙습니다.
안그래도 까페 24에 문의 해보고있는데요
혹시 해당부분을 skip 해도 상관없나요?

**Comment by ibin79** [comment]
네.  해당 라인만 주석 처리하셔서 설치 완료하시고요.  nptdate 이슈는 이후 별도로 해결하시면 됩니다.

**Comment by ChoHanDu** [comment]
바쁘신데 봐주셔서 고맙습니다.~~

**Comment by ibin79** [comment]
ntpdate 건 해결되시면 후기 남겨주시고요~ :)

**Comment by ChoHanDu** [comment]
후기는 어디다가 남길까요??? phpschool?? 어디다가 남기면 좋은지 알려주시면 남기도록 하겠습니다.

혹시몰라서 까페24 답변글 남겨드립니다.

현재 crontab에 시간동기화 설정 되어 있는 상태 입니다.
정상적으로 동기화 되는 부분 확인하였으니 확인해 보시기 바랍니다.
* crontab 설정
# time setting
14 3 * * * /usr/bin/rdate -s time.bora.net; /sbin/hwclock --systohc

* 시간 동기화
[root@q352-1966 ~]# /usr/bin/rdate -s time.bora.net; /sbin/hwclock --systohc

[root@q352-1966 ~]# uptime
 13:07:37 up  2:32,  3 users,  load average: 0.21, 0.08, 0.07

**Comment by ibin79** [comment]
여기다 남겨주시면 됩니다.

rdate 도 시간 동기화가 맞긴 하지만, 안정성과 정확도를 고려해 ntpdate 사용을 권장합니다만...

ntpdate 관련 답변은 없군요.

**Comment by ChoHanDu** [comment]
에러는 아니지만 리눅스 초짜인 저에게  도움주셔서 고맙습니다.
yum install 조차도 검색해보면서 할줄알아서 
까페24에 문제였는 상황까지 해결해주셔서 너무 고맙습니다.
이렇케 좋은 자동 설치 프로그램 만들어 주셔서 너무 너무 고맙습니다.

아마 저에겐 ntpdate 해결능력이 없으니 주석으로 그냥 지나고
실제 서버로 옮길때 해결해야할것 같네요~
다시한번 빠른 답변에 너무 고맙습니다.~~ 
그럼 더욱 더 좋은 프로그램 많이 많이 만들어주세요~~ ㅎㅎㅎㅎ
