### ISSUE TITLE
nginx PageSpeed, ModSecurity 지원 가능 여부

### ISSUE THREAD

**Issue by hot5g** [php79/stack#32]
현재 ModSecurity 모듈이 지원이 기본으로 되있는지요?
아니면 설치를 따로 해줘야 하는지요?

**Comment by ibin79** [comment]
ModSecurity 는 지원하지 않습니다.

**Comment by hot5g** [comment]
@ibin79 답글 감사드립니다.!

**Comment by hot5g** [comment]
@ibin79 
아. 죄송합니다. 한가지 더 여쭙겠습니다. mod_security 모듈를 설치하려면 리빌드해야 할거 같은데.
리빌드시 유의할 사항이 있을까요?

**Comment by ibin79** [comment]
stack 에서는 nginx 공식 저장소(http://nginx.org/packages/centos/7/x86_64/RPMS/)의 rpm 을 사용해 설치되고 있는데요.

stack 내에서는 nginx 컴파일 경험이 없어 도움이 될만한 내용이 없네요.

**Comment by hot5g** [comment]
@ibin79  stack 스크립트가 다 좋은데.. 외부모듈를 설치할때의 팁이 있었으면 좋겠습니다..
실 사용 서버에서 많이들 사용하는 모듈를 설치하지를 못하니.. 난감할때 많이 있는거 같습니다.
물론 많이 사용한다는 기준이 다 다르기에 힘든점도 분명 있다는것도 잘 알고 있습니다.^^;;

**Comment by ibin79** [comment]
우선 nginx 공식 저장소를 사용하는 이유는 '쉬운 업데이트'로 '보안 강화'에 목적을 두고 있습니다.

`yum update` 만으로 nginx, php, mariadb 모든 업데이트 관리가 가능한 장점이 있기 때문이지요.

또한 제가 stack 을 업데이트하지 않아도, 각각의 개발사 공식 저장소에서 업데이트가 이루어지는 장점도 있고요.

그런데 nginx 만 pagespeed, ModSecurity 등을 컴파일해서 제공하면, 초기 1회는 제공할 수 있더라도... 지속적인 업데이트가 가능할지 관건입니다.

그럼에도 이러한 nginx 추가 모듈의 필요성은 인지하고 있으므로, `초기 설치 + 지속적인 업데이트` 2가지를 충족할 방법을 고민중이긴 합니다.

**Comment by l2zeo** [comment]
@ibin79  마지막 구문이 너무 기대됩니다.저역시 바라는 부분이기도 하구요.

**Comment by l2zeo** [comment]
해당 이슈의 업데이트가 언제쯤 될까요? (실례인줄 알지만...)
:(

**Comment by ibin79** [comment]
우선  `지속적인 업데이트` 에 중점을 두고, 다음 사례들을 틈틈이 분석중입니다만...
아직 가능 여부와 일정은 정해지지 않았습니다. 

https://www.modpagespeed.com/doc/build_ngx_pagespeed_from_source

https://medium.com/@karljohnson/nginx-more-get-http-2-with-alpn-pagespeed-modsecurity-and-much-more-in-one-single-package-7d28a44d1854
 
https://github.com/karlgray/nginx-pagespeed-modsecurity/blob/master/build.sh

**Comment by l2zeo** [comment]
@ibin79 그렇군요 ^^. 서버이전을 앞두고 있어서 되도록 해당이슈 업데이트가 되는 시점에 이전을 생각했었는데 우선 이전을 하고 추후 업데이트가 된다면 그때 재설치 또는 해당 이슈 업데이트에 맞게 조정해야겠네요. 항상 노고에 감사합니다 :)

**Comment by ibin79** [comment]
@l2zeo stack 에 지속적인 관심 감사드립니다!

**Comment by l2zeo** [comment]
@ibin79 아직 많은분들이 모르고 계셔서 그렇지..stack를 알면 모든분들이 관심을 안가질수가 없겠지요.ㅎ
현재 저희측에 들어오는 서버세팅의 90%는 stack를 이용하여 약간의 커스터마이징을 하고 있습니다.
너무 편해요 ^^ 💯

**Comment by ibin79** [comment]
nginx 컴파일외엔 다른 방법이 없을 듯 하여, stack 방향과 맞지 않는 것 같습니다.
