### ISSUE TITLE
Let's Encrypt - auto renew

### ISSUE THREAD

**Issue by ibin79** [php79/stack#37]
# 크론 데몬에서 매일 새벽 갱신?

```
certbot-auto renew
```

# 인증서가 갱신된 경우만 nginx 재시작

- nginx 재시작전 `nginx -t`  성공시에만 재시작

**Comment by ibin79** [comment]
# 1차 코드 완료

# 테스트
- CentOS 6, 7 운영 서버에 각각 `/etc/cron.daily/certbot-auto-renew-cron.sh` 위치에 적용하여, 에러 유무 지켜봄.

**Comment by l2zeo** [comment]
@ibin79 드디어.. !

**Comment by l2zeo** [comment]
해당 부분은 언제쯤 업데이트가 될까요?? @.@

**Comment by ibin79** [comment]
현재 상황이...  저희 내부 서버들엔 적용해서 이상없는 것을 확인했고요.

초기 구축/업그레이드시 문제가 없는 방향으로 마무리지을 계획입니다만...

본업인 메인 프로젝트 일정이 빠듯해서, 투입할 시간이 나질 않고 있습니다. ㅜㅜ

크롬이 ssl 미적용 사이트에 대해 2018년 7월 부터 모든 페이지에 '안전하지 않음'으로 표시할 예정인지라, 늦어도 3월중엔 마무리해서 배포하려고 노력하고 있습니다.

> 크롬 업데이트 관련 - https://security.googleblog.com/2018/02/a-secure-web-is-here-to-stay.html

**Comment by l2zeo** [comment]
@ibin79  바쁘신 일정에도..!! 감사합니다.! 늦었지만 새해 복 많이 받으세요.

**Comment by ibin79** [comment]
- `/etc/cron.daily/certbot-auto-renew-cron.sh` 코드 자체는 몇개월 지켜본 결과 이상없이 동작함.
