### ISSUE TITLE
안녕하세요 질문드려요 504에러

### ISSUE THREAD

**Issue by anmkst** [php79/stack#40]
안녕하세요.
홈페이지에 예약작업이 실행이 안되어서 확인해보니 504 Gateway Time-out 에러가 뜨네요.

/etc/nginx/conf.d/홈페이지.conf 에

		proxy_connect_timeout 300;
		proxy_send_timeout 300;
		proxy_read_timeout 300;
		send_timeout 300;

추가를 해도 실행시간이 1분이면 에러가 나네요.

혹시 어디를 수정해야 하는지 실행시간을 늘릴수 있을까요?

부탁드리겠습니다...

**Comment by ibin79** [comment]
nginx error log 를 먼저 확인해보셔야 합니다만....

PHP 실행 시간이 길어짐에 따른 타임 아웃 문제라면, fastcgi_read_timeout 값을 기본 60초에서 늘려야 합니다.

메뉴얼 - http://nginx.org/en/docs/http/ngx_http_fastcgi_module.html#fastcgi_read_timeout

메뉴얼을 보니 선언 가능한 위치는 http, server, location 3가지 모두 가능하네요.

따라서 php79 stack 에서 'wordpress'라는 사이트로 만드셨을 경우, 다음처럼 추가해주시면 됩니다.

```
# vim /etc/nginx/conf.d/wordpress.conf

server {
...생략...
    include /root/stack/apps/fastcgi-php-html.conf;
    fastcgi_read_timeout 600s;
}

# service nginx reload
```

**Comment by anmkst** [comment]
해결되었습니다. 정말 감사합니다.

몇달동안 해결못한걸 해결해주시네요 ㅠㅠ

서버 잘 알지도 못하는데 nginx 로 넘어오면서 다시 아파치로 가야하나 너무 고민이 많네요

그때마다 도움을 주셔서 정말 감사합니다.

**Comment by ibin79** [comment]
잘 해결되셨다니 저도 기분이 좋네요! ^^
