### ISSUE TITLE
php53 다운로드를 위한 kr1.php.net 사이트 접속 불가.

### ISSUE THREAD

**Issue by manuzcom** [php79/stack#41]
`--2018-03-16 17:33:44--  http://kr1.php.net/distributions/php-5.3.29.tar.bz2
Resolving kr1.php.net (kr1.php.net)... 115.68.110.81
Connecting to kr1.php.net (kr1.php.net)|115.68.110.81|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-03-16 17:33:45 ERROR 404: Not Found.

PHP 컴파일이 실패하였습니다.

Exiting installer. (설치를 중단합니다.)
다음 명령이 실패하여, 설치가 중단되었습니다. (exit code: 1)
# scripts/centos7-php53-install.sh
`

위와 같이 에러가 나네요. 
kr1.php.net 이 접속되지 않을 경우를 대비한 미러링 사이트 몇개를 추가해두는 것이 좋지 않을까 합니다. 
저는 jp2 로 변경하여 설치 진행했습니다.

**Comment by ibin79** [comment]
국내 php 미러 사이트가 모두 사라졌네요...

http://php.net/mirrors.php

wget 에서 미러링 사이트를 입력하는 방법을 찾아봐야겠네요. ^^

**Comment by ibin79** [comment]
공식 저장소로 변경하였습니다.

```
http://php.net/distributions/php-5.3.29.tar.bz2
Resolving php.net (php.net)... 208.43.231.9, 2a02:cb41::7
Connecting to php.net (php.net)|208.43.231.9|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11396771 (11M) [application/octet-stream]
Saving to: ‘php-5.3.29.tar.bz2’
```
