### ISSUE TITLE
Let's Encrypt 설치 옵션 추가

### ISSUE THREAD

**Issue by ibin79** [php79/stack#42]
# 신규 설치

- stack.defaults.conf 에 `LETSENCRYPT=1` 옵션 추가

- 설치시 letsencrypt 사용할 경우에만 `/etc/cron.daily/certbot-auto-renew-cron.sh` 에 복사

# 업데이트

- stack.conf 에 직접 `LETSENCRYPT=1` 옵션을 추가하고, `install.sh` 재실행

- 기존 사용자들을 위한 별도 위키 제작

# ssl-install.sh? 개발

- nginx 설정 이후에 추가 고려?   (이미 추가된 사이트, 신규 사이트에 모두 설치 가능해야 함)

- 주의.  발급시 DNS 미설정, 방화벽으로 인한 오류 가능성 많음.  반드시 dry-run 성공후에 실제 요청하도록 함.

- Let's Encrypt 발급만 고려하며, 갱신은 크론탭에서 일괄 자동 갱신 #37 

# app-install.sh 에 `--ssl` 옵션 추가

- `--ssl` 옵션을 선언해야 ssl-install.sh 실행  (기존 사용자 호환성 고려)

- ssl-install.sh 는 발급 실패 가능성이 높으므로, 실패시에도 app-install.sh 과정은 정상 실행되고, 경고와 재시도 방법만 안내함.

**Comment by l2zeo** [comment]
드디어!!
수고 하셨습니다!
