### ISSUE TITLE
XE에서 첨부파일 업로드 시 첨부파일이 사라집니다.

### ISSUE THREAD

**Issue by sandol** [php79/stack#47]
어제 mysql data 경로 변경에 대해 질문하고 잘 해결되었습니다.
그 후에 정상적으로 운영중이던 사이트가 갑자기 게시판에 파일 첨부가 안되고 있습니다. ㅠㅠ (XE 1.8버전대를 사용중입니다.)
files폴더의 소유권한도 확인했고 따로 설정을 변경한 것이 없는데..
혹시 data경로가 변경될 경우 이런 문제가 발생할 수 있나요?

**Comment by ibin79** [comment]
DB 경로 변경은 DB 전체 오류는 있어도, 일부 프로그램 기능 오류를 유발하긴 어려울 것 같습니다만...

일단 원상 복구해보는 것이 좋을 것 같습니다.

**Comment by sandol** [comment]
자세히 확인해보니 z-php70.ini의 설정 중 대용량 업로드를 가능하게 설정을 해 둔 것이 원인인 것 같습니다. 이 것을 원복시키니 정상적으로 작동됩니다. 원인은 잘 모르겠네요. ^^; 빠른 답변 감사합니다.

**Comment by ibin79** [comment]
z-php79.ini 에는 설정 별로 설명을 해두었기 때문에,
시간 나실 때 설정을 1개씩 변경하며 테스트해보면 감을 잡으실 수 있을겁니다. ^^
