### ISSUE TITLE
stack 업데이트시 nginx 설정 확인 및 롤백 기능 고려

### ISSUE THREAD

**Issue by ibin79** [php79/stack#5]
### 배경

서버 스택의 우선 고려 대상은 안정성임.
#2 이슈와 관련하여, git 을 통해 현재 운영중인 서버와 충돌이 발생하는 nginx 설정이 배포되었을 경우 대응이 필요함.
### 대응

self-update.sh 실행전 nginx 설정 테스트.  오류시 중단.

git 업데이트후 nginx 설정 테스트.  오류시 git pull 롤백.   

단, 업데이트가 없을 경우는 롤백이 이루어지지 않아야 함.

**Comment by hot5g** [comment]
@ibin79 

궁금한것이 있습니다.

stack 업데이트가 될때, 기존의 php.ini(z-php79.ini) 설정과 같은 초기셋팅값과 다른 부분들이 stack의 초기셋팅값으로 돌아가는지요?

이 이슈가 이런 부분을 보완하는 부분인건가요?

**Comment by ibin79** [comment]
아뇨. 설치시 자동 추가된 z-php79.ini 등은 업데이트시에도 그대로 유지됩니다.

 /root/stack/apps/laravel51/common.conf 처럼 nginx 설정에서 공통 include되는 사항에 관한 이슈고요.

이 부분도 업데이트 정책을 수립하여, 기존 common.conf 는 수정하지 않고, 유지한 뒤 변경이 필요할 경우 common-v2.conf 형태로 추가하여 신규 '앱 자동 설치'시에만 적용되는 방향으로 고민중입니다.

**Comment by ibin79** [comment]
### 대응 v2

> '앱 자동 설치(app-install.sh)'시 nginx 설정에 자동 포함되는 /root/stack/apps/laravel51/common.conf 형태의 공통 파일은 업데이트시 수정하지 않도록 정책 수립하여, 롤백 필요성을 없앰.

self-update.sh 실행전 nginx 설정 테스트.  오류시 중단.

git 업데이트후 nginx 설정 재테스트.  오류시 메시지 출력.

**Comment by hot5g** [comment]
@ibin79 
아하. 그렇군요.
/root/stack/apps/fastcgi-php-html.conf 이런 공통으로 인크루드 되는 파일들에 대한 이슈인것이군요.

그럼 대응버전이 나오면 그때 업데이트를 해야겠네요ㅎ;

ps. 
무지해서 몇가지 더 여쭤봅니다 ㅡ.ㅡ;;
아래와 같은 conf도 영향을 받지 않는다는 말씀이신거죠?
/etc/nginx/nginx.conf 
OR 
/opt/remi/버전/root/etc/php-fpm.d/www.conf

**Comment by ibin79** [comment]
네. 현재 업데이트는 /root/stack 아래에 존재하는 파일들만 바뀌므로, 

다른 디렉토리의 설정들은 운영중인 사이트를 고려하여 임의 변경되지 않습니다. :)

**Comment by hot5g** [comment]
@ibin79 
자세한 답변 감사드립니다. 😄
