### ISSUE TITLE
php current stable

### ISSUE THREAD

**Issue by open2** [php79/stack#50]
7.3으로 바뀌었습니다.

![default](https://user-images.githubusercontent.com/2640011/51907740-11008e00-240b-11e9-8e82-80df1aaad077.PNG)

**Comment by ibin79** [comment]
remi 저장소에도 php 7.3 이 지원되네요.  

```
# yum update remi-release

# yum info php73-php

Version     : 7.3.1
```

 stack 에도 추가해야겠습니다.

**Comment by ibin79** [comment]
PHP 7.3 지원 완료,  기본 설치시엔 아직 7.1 로... 안정성을 위해...
