### ISSUE TITLE
방화벽이 막혀 있어서...

### ISSUE THREAD

**Issue by open2** [php79/stack#51]
기본 방화벽 포트는 apm 설치시에 풀어줘야 할 것 같습니다.

CentOS 7 - public zone에 80/443 2개 넣으면 됩니다.
firewall-cmd --permanent --zone=public --add-port=80/tcp
firewall-cmd --permanent --zone=public --add-port=443/tcp

**Comment by ibin79** [comment]
네.  방화벽 설정은 따로 해주셔야 하고요. ^^

firewalld 부분은 메뉴얼을 따로 준비하려했는데...  쉽지 않네요.

**Comment by open2** [comment]
탑스쿨님이 셋팅을 다 했는데, 웹 접속이 안된다고 해서 보니 방화벽...-..-...
웹의 방화벽 기본 포트는 풀어야 할 것 같습니다.
잘 모르는 분들이 대부분이라. ㅎㅎ

**Comment by ibin79** [comment]
위키로 일단 묶어 놨습니다. ^^

https://github.com/php79/stack/wiki/firewall
