### ISSUE TITLE
phpmyadmin을 git으로 설치할 때 오류

### ISSUE THREAD

**Issue by open2** [php79/stack#52]
Problem 1
    - Installation request for facebook/webdriver ^1.6 -> satisfiable by facebook/webdriver[1.6.0].
    - facebook/webdriver 1.6.0 requires ext-zip * -> the requested PHP extension zip is missing from your system

php에 ext-zip 미설치. 가끔 쓰는 ext 입니다.

**Comment by ibin79** [comment]
phpmyadmin 도 zip 확장 모듈이 필요하군요.  

향후 기본 설치시에 포함될 예정입니다.  #45

**Comment by open2** [comment]
phpmyadmin을 git 설치를 하면 7.2 등에서 session가 오류가 생기는데
stackoverflow에 답글을 추가한 것처럼 
config.inc.php에 session 디렉토리를 지정해주면 간단하게 해결 됩니다.

`$cfg['SessionSavePath'] = '/tmp';`

https://stackoverflow.com/questions/29632598/phpmyadmin-session-start-error-on-last-version/54591814#54591814

**Comment by open2** [comment]
phpmyadmin이 심포니 framework 으로 작성되어 있기 때문에
composer update도 해줘야 하므로
update.sh에 composer update 를 넣어두셔야 할 것 같습니다.
```

cd ~/master/public \
&& git pull origin STABLE
&& composer update
```

**Comment by ibin79** [comment]
#94 설치 개선되어 이슈 닫을게요.
