### ISSUE TITLE
nginx 보안설정 강화

### ISSUE THREAD

**Issue by open2** [php79/stack#54]
conf.d/0-php79.conf 에... 아래의 3줄을 추가... iframe 관련 보안방어

add_header X-Frame-Options SAMEORIGIN;
add_header X-Content-Type-Options nosniff;
add_header X-XSS-Protection "1; mode=block";

참조.
https://extrememanual.net/2059

**Comment by ibin79** [comment]
일괄 적용시엔 기존 사이트의 운영에 영향을 미칠 수 있어서,

옵션으로 제공하고 위키 등 문서로 설명하는 방안을 고민해봐야 할 것 같습니다.

**Comment by open2** [comment]
남의 사이트 컨텐츠를 iframe으로 몰래 가지고 와서 쓰는 곳이라면 문제가 되겠지만
그런 곳은 거의 없을 것 같습니다.
