### ISSUE TITLE
사소한 오류 제보

### ISSUE THREAD

**Issue by Cafri** [php79/stack#59]
./install.sh 실행해서 설치도중 아래와 메세지가 출력됩니다.
기능상으로 크게 문제없어보이긴 합니다만.. 어쨋든 오류이니 올려봅니다.
최초발생한 부분만 올렸는데 저 부분 이후로도 꾸준히 심볼릭링크가 아니라는 메세지가 나옵니다. 

Retrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-MariaDB
Importing GPG key 0x1BB943DB:
 Userid     : "MariaDB Package Signing Key <package-signing-key@mariadb.org>"
 Fingerprint: 1993 69e5 404b d5fc 7d2f e43b cbcb 082a 1bb9 43db
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-MariaDB
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : MariaDB-compat-10.3.18-1.el7.centos.x86_64                                                                                                                                                                               1/13
/sbin/ldconfig: /usr/lib/vmware-tools/lib64/libvmGuestLib.so/libvmGuestLib.so은(는) 심볼릭 링크가 아닙니다

**Comment by ibin79** [comment]
stack 과는 무관한 듯 보입니다.

다음 에러는 vmware-tools 설치 과정에서 동적 라이브러리 연결 과정에 문제가 있었던 것 같습니다.

이로 인해 yum 에서 패키지 설치시 동적 라이브러리(ld) 관련 위치에선 계속 해당 경고가 나오는 상황으로 추정됩니다.

```
/sbin/ldconfig: /usr/lib/vmware-tools/lib64/libvmGuestLib.so/libvmGuestLib.so은(는) 심볼릭 링크가 아닙니다
```

**Comment by Cafri** [comment]
저걸로 인해 생긴 문제인지는 정확히 모르겠는데 외부에서 80포트로 접근을 못하네요.
crul 명령어로 url 찍어보니 연결이 잘되고 있긴합니다만.. ㅜㅜ

**Comment by ibin79** [comment]
서버 로컬에서 `curl http://127.0.0.1`이 잘 된다면,

방화벽 포트 허용을 먼저 체크해보세요.    https://github.com/php79/stack/wiki/firewall

방화벽이 아니면 vmware 네트워크 문제일수도...

**Comment by Cafri** [comment]
방화벽은 아닌거 같습니다. 신규서버라 방화벽이 전부 열려있어서요.

**Comment by Cafri** [comment]
방화벽 문제가 맞는가봅니다. ㅠㅠ
centos7은 이번이 처음 써보는거라... 익숙해져야겠네요.
