### ISSUE TITLE
기존 사용하던 php버전을 업그레이드 하려할때.

### ISSUE THREAD

**Issue by hot5g** [php79/stack#64]
기존에 사용하던 php버전을 업그레이드 하려할때,
`server {
    set $APP_BACKEND php54_backend;`

이렇게 5.4버전에서 7.2버전으로 업그레이드 하려면,
`server {
    set $APP_BACKEND php72_backend;`

이런식으로 변경만 해주면 되는지요?

이미 php7.2는 설치한 상황이라는 가정하에요.

**Comment by ibin79** [comment]
네. 맞습니다.
