### ISSUE TITLE
mariadb kaist ftp 다운으로 인한 yum 실행 문제

### ISSUE THREAD

**Issue by ibin79** [php79/stack#65]
### 배경

http://ftp.kaist.ac.kr/ 서비스가 중단되어 mariadb 저장소 접근이 불가한 문제 발생.

> https://twitter.com/kaist_ftp

### 장애

`yum update` 로 전체 패키지 업데이트시, MariaDB 저장소 연결이 되지 않아 전체 업데이트가 안되는 문제 발생.

```
 One of the configured repositories failed (MariaDB),
...
     3. Run the command with the repository temporarily disabled
            yum --disablerepo=mariadb ...
```

### 임시대응

1. `yum --disablerepo=mariadb update`형태로 mariadb 저장소만 일단 무시하고 업데이트 가능.

2. mariadb 저장소는 kaist 대신 공식 저장소로 변경 (속도는 느림)

```
vi /etc/yum.repos.d/MariaDB.repo

#baseurl=http://yum.mariadb.org/10.3/centos7-amd64
baseurl=http://ftp.kaist.ac.kr/mariadb/yum/10.3/centos7-amd64/

->

baseurl=http://yum.mariadb.org/10.3/centos7-amd64
#baseurl=http://ftp.kaist.ac.kr/mariadb/yum/10.3/centos7-amd64/

```

> 주의) 현재 사용중인 mariadb 버전( 10.1, 10.3, ...) 을 확인하여 유지해야 함.

### 후속대책

공식 미러리스트에서 국내는 현재 kaist 만 운영중이라, 미러 리스트 및 미러 추가가 필요함.

https://mariadb.com/kb/en/library/mirror-sites-for-mariadb/

1. mariadb mirrorlist 만 수작업으로 구축하여 운영?   

> 미러 추가/수정 관리를 해주어야 함.

2. mariadb 국내 미러 운영?

> 네트워크 회선 비용 고려?  대역폭 제한으로 일종의 백업 미러 용도로?  구축 및 관리에 들어가는 시간은...? ㅜㅜ

**Comment by ibin79** [comment]
### 테스트

mariadb 공식 저장소로 테스트 완료.

```
# cat /etc/yum.repos.d/MariaDB.repo 
[mariadb]
name=MariaDB
baseurl=http://yum.mariadb.org/10.4/centos7-amd64
#baseurl=http://ftp.kaist.ac.kr/mariadb/yum/10.4/centos7-amd64/
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-MariaDB
gpgcheck=1
# mysql --version
mysql  Ver 15.1 Distrib 10.4.10-MariaDB, for Linux (x86_64) using readline 5.1
```

**Comment by onlydev** [comment]
이 문제로 검색하다 방문하게 되었네요.
현재 https://ftp.harukasan.org/mariadb/repo/ 에서 사용가능하네요.
https://ftp.harukasan.org/mariadb 로 접속시 mariadb 사이트로 리다이렉트 되지만 위 사이트로 직접 접속하면 정상적으로 업데이트가 되고 있습니다.
