### ISSUE TITLE
letsencrypt의 와일드카드 적용후 갱신시 이러한 에러가 출력됩니다.

### ISSUE THREAD

**Issue by l2zeo** [php79/stack#72]
수동으로 갱신하려하니 아래와 같은 에러가 출력되네요.

해당 도메인은 와일드카드로 ssl를 설치했었습니다.

Attempting to renew cert (도메인) from /etc/letsencrypt/renewal/도메인.co.kr.conf produced an unexpected error: The manual plugin is not working; there may be problems with your existing configuration.

The error was: PluginError('An authentication script must be provided with --manual-auth-hook when using the manual plugin non-interactively.',). Skipping.

All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/도메인.co.kr/fullchain.pem (failure)

찾아보니 

./certbot-auto --server https://acme-v02.api.letsencrypt.org/directory -d “*.ctsig.com” --manual --preferred-challenges dns-01 certonly

이런식으로 해줘야 하는거 같은데요. 와일드카드 적용된 도메인에 대해서도 수동 또는 자동갱신이 되도록 해야 할거 같습니다 ㅠㅠ

https://certbot.eff.org/docs/using.html#pre-and-post-validation-hooks

**Comment by ibin79** [comment]
와일드카드 도메인은 dns 인증이 필요해서, stack 기본 설정인 http 기반 자동 인증과는 차이가 있습니다.

관련 해결책을 제가 단시간내에 제시해드리긴 어려울 것 같습니다.

**Comment by l2zeo** [comment]
close
