### ISSUE TITLE
open files은 어디서 조정할수 있는지요?

### ISSUE THREAD

**Issue by l2zeo** [php79/stack#73]
`vi /usr/lib/systemd/system/mariadb.service`

```
LimitNOFILE=65535
```

`vi /etc/my.cnf.d/z-php79.cnf`

```
[mysqld_safe]
open-files-limit=65535
```

위처럼 변경해보았지만 변경되지 않아 문의 드립니다.

`show global variables like 'open%';`

```
+------------------+-------+
| Variable_name    | Value |
+------------------+-------+
| open_files_limit | 9231  |
+------------------+-------+
1 row in set (0.001 sec)
```

**Comment by ibin79** [comment]
해당 제한으로 인한 에러는 대부분 OS 레벨에서의 설정 변경으로 해결하는 케이스가 많습니다.

1안) 서버 재부팅후 해결


```
# ulimit -a|grep open
open files                      (-n) 1024

vi /etc/security/limits.conf

*               soft    nofile  20480
*               hard    nofile  40960
```


2안) `ulimit -n 20480` 등 커맨드 라인 실행후, mariadb  등 open files 제한된 서비스 재시작.  (재부팅후 적용을 위해선 1안 필수)

--- 

### 참고

https://www.cyberciti.biz/faq/linux-unix-nginx-too-many-open-files/

**Comment by l2zeo** [comment]
close
