### ISSUE TITLE
phpmyadmin 자동 설치 안됨

### ISSUE THREAD

**Issue by doublek13** [php79/stack#75]
잘 사용하고있습니다.
네이버 ncloud 이용하여 이용중입니다.
몇가지 오류 및 문의 드립니다.
오류1 : 워드프레스 설치중 app/wordpress/install.sh 에서 ko 한국어 버전이 다운이 안되어 아래처럼 변경하여 설치하니 잘됩니다. && ~/wp core download  \

오류2: ssl은 자동설치시 오류가 납니다. 수동설치방법 아래처럼 하였습니다.
certbot certonly --manual -d *.도메인.co.kr -d 도메인.co.kr --agree-tos --manual-public-ip-logging-ok --preferred-challenges dns-01 --server https://acme-v02.api.letsencrypt.org/directory 

위 명령어로 치고 dns 레코드 (txt) 업데이트 방법으로 해결하였습니다.

문의 : ./app-install.sh --user=paros1 --domain=도메인.com --app=phpmyadmin --app=wordpress --php=74

위 명령어시 워드프레스 설치는 잘되는데 phpmyadmin 파일은 설치가 안됩니다.
phpmyadmin 자동 설치가 안되어 문의드립니다. 
설정방법이 미숙하여 좀 알려주시면 감사하겠습니다.

**Comment by ibin79** [comment]
한번에 1개 앱만 설치할 수 있습니다.

phpmyadmin 은 별도 서브 도메인을 지정하여 등록해주세요.

`--app=phpmyadmin --app=wordpress`   이렇게 하면 마지막에 선언된 wordpress 만 인식됩니다.


---

letsencrypt 멀티 도메인 성공 사례를 남겨주셨네요. ^^

**Comment by doublek13** [comment]
감사합니다 
wordpress 빼고 phpmyadmin 만 넣어서 해보겠습니다
답변 너무 감사합니다~~

나의 iPhone에서 보냄

**Comment by doublek13** [comment]
> 한번에 1개 앱만 설치할 수 있습니다.
> 
> phpmyadmin 은 별도 서브 도메인을 지정하여 등록해주세요.
> 
> `--app=phpmyadmin --app=wordpress` 이렇게 하면 마지막에 선언된 wordpress 만 인식됩니다.
> 
> letsencrypt 멀티 도메인 성공 사례를 남겨주셨네요. ^^
> 
> * [ ]  워드프레스 최초 설치 방법은 체크 필요

서브도메인 이용하여 phpmyadmin 만 설치 >  IP 접속가능하게 설정후 접속하면 아래 메세지가 뜹니다.
구글에서 위 에러에 관한 링크를 찾았습니다. phpmyadmin 은 이미 설치되어있는데 다시 설치를 해야하네요. stack 에서 받아오는 phpmyadmin 이 다른버전인가요? 다르다면 어떻게 바꿀수있나요?

File /home/phpmyadmin/master/public/vendor/autoload.php missing or not readable.
Most likely you did not run Composer to install library files.
 
https://m.blog.naver.com/PostView.nhn?blogId=gadguy&logNo=221009377274&proxyReferer=https%3A%2F%2Fwww.google.com%2F

**Comment by ibin79** [comment]
기본 옵션 값은 다음처럼 git clone 을 통해 설치됩니다.

https://github.com/php79/stack/blob/master/apps/phpmyadmin/install.sh


위 기본 설치를 생략하려면 다음 옵션을 주면 됩니다.

```
# ./app-install.sh 


  --skip-install       (선택) 계정 추가 및 nginx 설정까지만 진행하고, 앱 자동 설치(install.sh)는 생략합니다.
                Tip) 이미 제작된 소스로 설치하거나, 직접 소스를 설치하실 경우에 사용하세요.
```


물론 자동 설치된 것을 삭제하고 직접 설치해셔도 무방하고요.

**Comment by doublek13** [comment]
./app-install.sh --user=phpmyadmin --domain=27.96.135.175 --app=phpmyadmin --php=74
PHPMYADMIN 설치후, 접속 IP 추가후 아래 메세지가 나오는데 해결 방안이 없을까요?

에러메세지 : 
File /home/phpmyadmin/master/public/vendor/autoload.php missing or not readable.
Most likely you did not run Composer to install library files.
![Snip20200416_38](https://user-images.githubusercontent.com/28985733/79413626-6c547700-7fe3-11ea-901a-1a95f2534b21.png)

**Comment by ibin79** [comment]
안내 문구에 나온대로 .../public 으로 이동하셔서 컴포터 설치 명령을 실행해주시면 됩니다.


```
composer install -vvv
```

**Comment by doublek13** [comment]
> 안내 문구에 나온대로 .../public 으로 이동하셔서 컴포저 설치 명령을 실행해주시면 됩니다.
> 
> ```
> composer install -vvv
> ```

위 위치로 갈려면 Home > phpmyadmin > master > publick 으로 이동해야되는데, ls 치면 stack 이라는 폴더밖에 갈 수 없는데 어떻게 해야하나요?

![Snip20200416_40](https://user-images.githubusercontent.com/28985733/79418465-ab88c500-7fef-11ea-95b0-5ebff366eee5.png)

**Comment by ibin79** [comment]
linux cd 명령에 대해 검색해보셔야 겠어요.

**Comment by doublek13** [comment]
> linux cd 명령에 대해 검색해보셔야 겠어요.
stack 안에서만 이동이 가능하게되어있네요. 명령어가 없는듯 합니다.
혹시 app 설치시 app-install.sh 에서 설치 폴더를 stack 하위 폴더로 생성하여 설치가능한가요?
phpmyadmin 때문에 몇달째 고생중입니다. 도와주세요~

**Comment by doublek13** [comment]
> linux cd 명령에 대해 검색해보셔야 겠어요.

cd / 명령어로 폴더 접근후 composer install -vvv 해도 안되네요.
해결 방법이 없을까요?

**Comment by ibin79** [comment]
`composer install -vvv` 시 어떤 에러로 안되는지 정보가 필요합니다.

**Comment by doublek13** [comment]
> `composer install -vvv` 시 어떤 에러로 안되는지 정보가 필요합니다.
> 
> 위 에러대로라면, 다음 명령 사용시 어떤 에러가 보여지나요?
> 
> ```
> cd /home/phpmyadmin/master/public
> composer install -vvv
> ```
답변 감사합니다!
phpmyadmin 70 ~ 73 까지 에러가 나며 , 기본 값인 74 에서는 phpmyadmin 로긴 페이지 까지 보입니다.
https 오류가 아래처럼 나와서 ssl 적용을 하였는데도 https 에러 메세지가 계속 나옵니다.
(SSL 은 위에 올려놓은 방법으로다른 사이트에서 잘 작동 중에있습니다.)
![Snip20200522_4](https://user-images.githubusercontent.com/28985733/82724168-2475ed80-9d0f-11ea-9010-a70129770fb1.png)

**Comment by doublek13** [comment]
> > `composer install -vvv` 시 어떤 에러로 안되는지 정보가 필요합니다.
> > 위 에러대로라면, 다음 명령 사용시 어떤 에러가 보여지나요?
> > ```
> > cd /home/phpmyadmin/master/public
> > composer install -vvv
> > ```
> 
> 답변 감사합니다!
> phpmyadmin 70 ~ 73 까지 에러가 나며 , 기본 값인 74 에서는 phpmyadmin 로긴 페이지 까지 보입니다.
> https 오류가 아래처럼 나와서 ssl 적용을 하였는데도 https 에러 메세지가 계속 나옵니다.
> (SSL 은 위에 올려놓은 방법으로다른 사이트에서 잘 작동 중에있습니다.)
> 도메인 적용은 php.xxxxx.com 으로 하였습니다.
> 
> * 이제까지 거의 모든 에러 및 설치 부분에서 해결했는데 phpmyadmin 안되니 답답하네요. 도와주세요...
> 
> ![Snip20200522_4](https://user-images.githubusercontent.com/28985733/82724168-2475ed80-9d0f-11ea-9010-a70129770fb1.png)

위 화면에서 로그인 하면 아래 스크린 샷 처럼 나옵니다.
뭐가문제인지 모르겠네요...도와주세요..
![Snip20200525_1](https://user-images.githubusercontent.com/28985733/82781023-bc044900-9e93-11ea-889c-e3c84ce23605.png)

**Comment by ibin79** [comment]
#94 설치 개선되어 이슈 닫을게요.
