### ISSUE TITLE
[제안] Default conf 파일의 내용 중 PHPXX를 모두 0으로 두는 건

### ISSUE THREAD

**Issue by aeharvlee** [php79/stack#81]
디폴트  설정을 0으로 두고 README.md 가이드에 설치하길 원하는 버전을 기재하게끔 하면 어떨까요?

얼마 전, `stack.conf` 를 별도로 만들고 설치를 진행하는데 `stack.defaults.conf`의 `PHP74=1` 값이 중복으로 읽혀서 2개의 버전이 설치되는 일을 겪었습니다.

실제 프로덕션에서 사용하시던 PHP버전을 그대로 설치하려고 시도할 때, 
비슷한 일을 다른 분들도 겪으실 수 있다는 생각이 들어 이렇게 제안드립니다.
(재직 중인 회사에서는 PHP70을 사용하고 있습니다.)

전부 0으로 두고 원하는 설정값을 설정해서 쓰게끔 가이드에 추가하면, 이런 혼선이 없어지고 적어도 사람들이 사용 전 README를 한 번씩은 정독하면서 프로젝트에 대한 이해도, 관심도 높아질 것이라 기대가 됩니다.

괜찮으시다면 제가 PR 날려도 될까요? 별 수정 내용은 없지만요.

**Comment by ibin79** [comment]
저희 회사도 현재 주력은 PHP 7.0 인데... 7.4 로 옮겨가고 있어서 동일한 경험이 있는데요.

처음 의도한 방향이 stack.conf 를 따로 수정하지 않아도, 쉬운 첫 사용을 위해 PHP가 1개는 자동 설치되어야 한다고 생각합니다.   따라서 이 방향을 바꾸긴 어렵습니다.

대신 위키에 다음 내용 정도를 추가하는 선으로 안내하는 방향으로 정리해야할 것 같습니다.


### stack.conf 에 PHP74 설정이 없어서, PHP 7.4 가 잘못 설치된 경우 삭제 방법

```
yum erase php74*
```

```
// stack.conf  에 추가하여, install.sh  실행시 설치되지 않도록 함

PHP74=0
```

**Comment by aeharvlee** [comment]
답변 감사합니다.
해당 이슈는 클로즈 하도록 하겠습니다.
