### ISSUE TITLE
문의드립니다.

### ISSUE THREAD

**Issue by zephyros91** [php79/stack#85]
2021년 07월 07일 기준 최신버전을 설치하고 나서
./app-install 로 설치를 하고나면 
꼭 403 Forbidden 오류가 나는데 
어떤문제가 있어서 이렇게 되는건지 궁금합니다.

이전버전을 설치한 서버를 확인 해보니
nginx.conf 설정이 변경된거 같은데 이전버전으로는 설치가 불가능할까요 ?

**Comment by zephyros91** [comment]
기존과 변경된점이 있다면
nginx : master > nginx : worker 정도로 변경된거 같은데 해당 내용이 이슈가 있을 수 있을까요 ?

**Comment by ibin79** [comment]
stack 은 최초 nginx 설치시 nginx.conf 파일에서 user, worker_processes 설정만 변경하고, 나머진 변경하지 않습니다.

우선 403 접근시 nginx 에러 로그에 어떤 메세지가 있는지 확인해보셔야 합니다.

```
ll -t /var/log/nginx/|more
```

**Comment by zephyros91** [comment]
궁금한게 지금은 최신버전이 1.2.1 로 되어 있는데
1.1.0 버전으로 git 해오는 방법은 없을까요 ?
1.1.0 버전으로 설치를 한다고 해도 nginx 는 최신버전으로 설치가 될까요?

**Comment by ibin79** [comment]
네. nginx 는 버전을 별도 지정하지 않고, 저장소내 최신 버전을 기준으로 설치하도록 되어 있습니다.

**Comment by zephyros91** [comment]
흠 .. 해결방법을 연구 해봐야 겠네요 ㅠㅠㅠ ...
답변 감사합니다.
혹시 지금 OS 재설치하고 다시 최신버전으로 설치 하려고 하는데 .
거기서 나오는 문제가 이해가 안된다면 질문드려도 괜찮을까요 ?

**Comment by ibin79** [comment]
403 Forbidden 에러가 발생하는 원인은 다양하므로, nginx 에러 로그를 확인해야 합니다.

에러 로그 확인, 설정 파일의 차이점 등 세부적인 사항이 없이는 해결이 어렵습니다.

**Comment by zephyros91** [comment]
2021/07/08 18:09:39 [error] 28803#28803: *15 "/home/xxxx/master/public/index.php" is forbidden (13: Permission denied), client: xx.xx.xx.xx, server: xxxx.xxx, request: "GET / HTTP/1.1", host: "xxxx.xxx"
라는 문구가 나와서 해당계정.conf 를 확인 해보았습니다.
root경로 역시 이상없었고
권한문제인가 싶어서 chmod -R 755 /home/xxxx/master/public/ 라는 경로의 권한도 바꿔봤습니다.
하지만 동일하게 문제가 나오는데
추가적으로 해봐야 할 명령어 등이 있을까요 ?

**Comment by zephyros91** [comment]
--------------
해결방법을 찾았습니다.
nginx 가 설치되면서 기본적인 user 가 nginx 로 설정되어 있는데
해당 내용을 nobody로 변경 해주니까 정상 가동 되는거 확인 했습니다.
번거롭게 해드려서 정말 죄송합니다.
아직 웹이나 해당 내용이 대해서 잘 모르는 부분이 있어서 공부하고 있다보니 해결방법이 보였습니다.

**Comment by ibin79** [comment]
원인을 잘 찾아서 해결하셨네요.  ^^

**Comment by zephyros91** [comment]
혹시 추가 질문을 드려도 괜찮을지 모르겠습니다만 ..
그누보드 5 설치하려고 하다보니 ..
2021/07/08 18:50:07 [crit] 30036#30036: *1 open() "/var/lib/nginx/tmp/client_body/0000000001" failed (13: Permission denied), client: xxx.xxx.xx.xx, server: teamluna.net, request: "POST /install/install_config.php HTTP/1.1", host: "teamluna.net", referrer: "http://xxxx.xxx/install/"
라는 오류가 나오고 있는데 ...
해당 경로인 /var/lib/nginx/tmp 경로를 chown -R nobody:nobody로 변경 처리 해주었습니다.
그 뒤에도 저런 오류가 나오면서 500 Internal Server Error 라는 오류가 여전히 유지되고 있는데
해당 내용에 대한 도움이나 힌트를 좀 받을 수 있을까요 ?
