### ISSUE TITLE
Let's Encrypt 루트 인증서인 DST Root CA X3 만료는 상관이 없을까요?

### ISSUE THREAD

**Issue by l2zeo** [php79/stack#87]
https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/

DST가 9월 30일에 만료된다고 하던데. stack에서 발급하는 인증서는 문제가 없을까요?

**Comment by ibin79** [comment]
windows 10 에서는 날짜를 10/1 로 변경해보면, 다음처럼 브라우저에서 새로운 ISRG Root X1 를 인식하여 문제없는 것으로 보입니다.

- 크롬 - 9/29 은 DST Root CA X3 사용
![image](https://user-images.githubusercontent.com/6302755/135149637-cbf64352-07dd-402e-85fb-f25705fcbfc5.png)

- 크롬 - 10/1 은 ISRG Root X1 사용

![image](https://user-images.githubusercontent.com/6302755/135149062-b3af56f6-783f-4ce7-af74-5c2256d3dd72.png)


- IE 11 - 9/29, 10/1 일 동일하게 DST Root CA X3 에서  ISRG Root X1 교차로 호출하여 인증 성공
![image](https://user-images.githubusercontent.com/6302755/135149233-0e86d1f2-5af3-4788-9001-83859cd1d76b.png)



다만 하위 브라우저 호환성은 다음과 같은데, 실제 잘 동작할지는 지켜봐야할 것 같네요.


https://letsencrypt.org/docs/certificate-compatibility/

**Comment by ibin79** [comment]
- Windows 7 + IE 11 에서 10/1 변경후,  ISRG Root X1 사용하여 잘 됨.

![image](https://user-images.githubusercontent.com/6302755/135202734-bff486a7-7ca5-429a-87b1-14a7959e8604.png)

**Comment by ibin79** [comment]
### Windows 10 root ca 수동 설치

> Windows 10 업데이트 완료후에도 'ISRG Root X1' 인증서가 없는 PC 발견되어, 수동 설치 안내 불가피함.


	1. 파일 다운로드 - https://letsencrypt.org/certs/isrgrootx1.der
	2. 윈도우 탐색기에서 해당 파일에 마우스 오른쪽 단추를 눌러, [인증서 설치] 클릭, [열기] 클릭
	3. '로컬 컴퓨터' 선택
	4. '모든 인증서를 다음 저장소에 저장' 선택후 '찾아보기' 클릭
	5. '신뢰할 수 있는 루트 인증 기관' 선택하고 [확인] 클릭하고, [다음] 클릭
	6. [마침] 누르면 루트 인증서 가져오기가 완료되고, 브라우저를 재실행하면 인증 문제가 해결됩니다.
